CREATE TABLE `salesordertransformedset_schema` (
   `order_id` text,
   `order_date` date DEFAULT NULL,
   `ship_date` date DEFAULT NULL,
   `ship_mode` text,
   `customer_name` text,
   `segment` text,
   `state` text,
   `country` text,
   `market` text,
   `region` text,
   `product_id` text,
   `category` text,
   `sub_category` text,
   `product_name` text,
   `sales` decimal(10,2) DEFAULT NULL,
   `quantity` int DEFAULT NULL,
   `discount` decimal(3,2) DEFAULT NULL,
   `profit` decimal(10,2) DEFAULT NULL,
   `shipping_cost` decimal(10,2) DEFAULT NULL,
   `order_priority` text,
   `year` int DEFAULT NULL,
   `delivery_days` int DEFAULT NULL
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
